version: '3.8'
services:

# Database container
  db:
    image: mongo
    container_name: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - 27017:27017
    volumes:
      - ./docker-compose/mongo/data:/data/mongo
    restart: always
    networks:
      - chat-network 

  host:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: host
    environment:
      PORT: ${PORT}
      DATABASE_HOST: ${DATABASE_HOST}
      ACCESS_TOKEN_SECRETE: ${ACCESS_TOKEN_SECRETE}
      REFRESH_TOKEN_SECRETE: ${REFRESH_TOKEN_SECRETE}
      MIN_TEXT_SEARCH_LENGTH: ${MIN_TEXT_SEARCH_LENGTH}
    ports:
      - 3001:3001
    restart: always
    networks:
      - chat-network   

networks:
  chat-network:     
